version: '3.5'
services:
  webapp-service:
    #    build: ./webapp
    image: node:10
    container_name: votacultura-web
    user: "root"
    working_dir: /home/node/app
    #    healthcheck:
    #      test: ["CMD", "curl", "-sS", "http://localhost:8080"]
    #      #      test: ["CMD-SHELL", "node /home/node/app/healthcheck.js"]
    #      interval: 20s
    #      timeout: 5s
    #      retries: 3
    volumes:
    - ./webapp:/home/node/app
    command:
      #   sh -c 'npm i && npm run serve'
      #   sh -c 'npm run serve'
      sh -c 'npm run build'
    #      sh -c 'npm run watch'
    ports:
    - "8080:8080"
    environment:
    - NODE_ENV=production
    networks:
    - votacultura_network

  api-service:
    container_name: votacultura-api
    build: ./api
    image: mds/votacultura-php-fpm:1.2.1
    working_dir: /application
    volumes:
    - ./api:/application
    #- ./api/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
    - APP_ENV=local
    restart: on-failure
    networks:
    - votacultura_network

  webserver-service:
    build:
      context: ./api
      dockerfile: WebserverDockerfile
      args:
        EXPOSE_PORT: 80
    image: mds/votacultura-webserver-nginx:1.0.0
    container_name: votacultura-webserver
    working_dir: /application
    volumes:
    - ./api:/application
    - ./api/docker/webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "88:80"
    depends_on:
    - api-service
    networks:
    - votacultura_network

  webapp-webserver-service:
    image: nginx:1.17-alpine
    container_name: votacultura-webapp-webserver
    working_dir: /usr/share/nginx/html
    volumes:
    - ./webapp/dist:/usr/share/nginx/html
    - ./webapp/docker/webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    networks:
    - votacultura_network

# docker network create votacultura_network

networks:
  votacultura_network:
    name: votacultura_network
    driver: bridge
