/* eslint-disable import/prefer-default-export */
export const DEFINIR_RECURSO = 'DEFINIR_RECURSO';
export const OBTER_DADOS_RECURSO = 'OBTER_DADOS_RECURSO';
export const LISTAR_RECURSOS = 'LISTAR_RECURSOS';
export const ATUALIZAR_RECURSO_INSCRICAO_LISTA = 'ATUALIZAR_RECURSO_INSCRICAO_LISTA';
