/* eslint-disable import/prefer-default-export */
export const DEFINIR_CONSELHO = 'DEFINIR_CONSELHO';
export const OBTER_DADOS_CONSELHO = 'OBTER_DADOS_CONSELHO';
export const BUSCAR_PERFIS = 'BUSCAR_PERFIS';
export const LISTAR_CONSELHOS = 'LISTAR_CONSELHOS';
export const LISTAR_CONSELHOS_HABILITACAO = 'LISTAR_CONSELHOS_HABILITACAO';
export const LISTAR_CONSELHOS_PARCIALMENTE_HABILITADOS = 'LISTAR_CONSELHOS_PARCIALMENTE_HABILITADOS';
export const MOSTRAR_MODAL_VISUALIZACAO = 'MOSTRAR_MODAL_VISUALIZACAO';
export const LISTAR_INDICACOES_CONSELHO = 'LISTAR_INDICACOES_CONSELHO';
export const DELETAR_INDICACAO_CONSELHO = 'DELETAR_INDICACAO_CONSELHO';
export const CONCLUIR_INDICACAO = 'CONCLUIR_INDICACAO';
export const OBTER_LISTA_PARCIAL_INDICADOS = 'OBTER_LISTA_PARCIAL_INDICADOS';