/* eslint-disable import/prefer-default-export */
export const DEFINIR_CONSELHO = 'DEFINIR_CONSELHO';
export const OBTER_DADOS_CONSELHO = 'OBTER_DADOS_CONSELHO';
export const BUSCAR_PERFIS = 'BUSCAR_PERFIS';
export const LISTAR_CONSELHOS = 'LISTAR_CONSELHOS';
export const LISTAR_CONSELHOS_HABILITACAO = 'LISTAR_CONSELHOS_HABILITACAO';
export const MOSTRAR_MODAL_VISUALIZACAO = 'MOSTRAR_MODAL_VISUALIZACAO';