CREATE TABLE tb_perfil (
	co_perfil            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	no_perfil            varchar(255)  NOT NULL ,
	ds_perfil            varchar(255)   ,
	st_ativo             bool DEFAULT true  ,
	CONSTRAINT pk_tb_perfil_co_perfil PRIMARY KEY ( co_perfil )
 );

CREATE TABLE tb_usuario (
	co_usuario           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	no_cpf               text  NOT NULL ,
	no_nome              varchar(255)  NOT NULL ,
	no_email             varchar  NOT NULL ,
	ds_senha             varchar(255)  NOT NULL ,
	dt_nascimento        date  NOT NULL ,
	ds_codigo_ativacao   varchar(255)   ,
	ds_codigo_alteracao   varchar(255)   ,
	dt_cadastro          date  NOT NULL ,
	dt_ultima_atualizacao date DEFAULT current_date  ,
	st_ativo             bool DEFAULT true NOT NULL ,
	CONSTRAINT pk_usuario_co_usuario PRIMARY KEY ( co_usuario )
 );

COMMENT ON COLUMN tb_usuario.no_email IS 'E-mail do Usuario';

COMMENT ON COLUMN tb_usuario.ds_senha IS 'Senha do Usuario';

COMMENT ON COLUMN tb_usuario.ds_codigo_ativacao IS 'Hash utilizado para ativação do Usuario';

COMMENT ON COLUMN tb_usuario.st_ativo IS 'Situação do Usuario';

CREATE TABLE rl_usuario_perfil (
	co_usuario_perfil    integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	co_usuario           integer  NOT NULL ,
	co_perfil            integer  NOT NULL ,
	st_perfil_atual      bool DEFAULT true ,
	CONSTRAINT pk_rl_usuario_perfil_co_usuario_perfil PRIMARY KEY ( co_usuario_perfil ),
	CONSTRAINT fk_usuario_perfil_usuario FOREIGN KEY ( co_usuario ) REFERENCES tb_usuario( co_usuario )  ,
	CONSTRAINT fk_usuario_perfil_perfil FOREIGN KEY ( co_perfil ) REFERENCES tb_perfil( co_perfil )
 );
