CREATE TABLE tb_perfil (
	co_perfil            integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	no_perfil            varchar(255)  NOT NULL ,
	ds_perfil            varchar(255)   ,
	st_ativo             bool DEFAULT true  ,
	CONSTRAINT pk_tb_perfil_co_perfil PRIMARY KEY ( co_perfil )
 );

CREATE TABLE tb_usuario (
	co_usuario           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	no_cpf               text  NOT NULL ,
	no_nome              varchar(255)  NOT NULL ,
	no_email             varchar  NOT NULL ,
	ds_senha             varchar(255)  NOT NULL ,
	dt_nascimento        date  NOT NULL ,
	ds_codigo_ativacao   varchar(255)   ,
	ds_codigo_alteracao   varchar(255)   ,
	dt_cadastro          date  NOT NULL ,
	dt_ultima_atualizacao date DEFAULT current_date  ,
	st_ativo             bool DEFAULT true NOT NULL ,
	CONSTRAINT pk_usuario_co_usuario PRIMARY KEY ( co_usuario )
 );

COMMENT ON COLUMN tb_usuario.no_email IS 'E-mail do Usuario';

COMMENT ON COLUMN tb_usuario.ds_senha IS 'Senha do Usuario';

COMMENT ON COLUMN tb_usuario.ds_codigo_ativacao IS 'Hash utilizado para ativação do Usuario';

COMMENT ON COLUMN tb_usuario.st_ativo IS 'Situação do Usuario';

CREATE TABLE rl_usuario_perfil (
	co_usuario_perfil    integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	co_usuario           integer  NOT NULL ,
	co_perfil            integer  NOT NULL ,
	st_perfil_atual      bool DEFAULT true ,
	CONSTRAINT pk_rl_usuario_perfil_co_usuario_perfil PRIMARY KEY ( co_usuario_perfil ),
	CONSTRAINT fk_usuario_perfil_usuario FOREIGN KEY ( co_usuario ) REFERENCES tb_usuario( co_usuario )  ,
	CONSTRAINT fk_usuario_perfil_perfil FOREIGN KEY ( co_perfil ) REFERENCES tb_perfil( co_perfil )
 );

 CREATE TABLE tb_uf (
	co_ibge              integer  NOT NULL ,
	sg_uf                char(2)  NOT NULL ,
	no_uf                varchar(50)  NOT NULL ,
	CONSTRAINT pk_uf_coibge PRIMARY KEY ( co_ibge )
 );

COMMENT ON COLUMN tb_uf.co_ibge IS 'chave primária da tabela';

COMMENT ON COLUMN tb_uf.sg_uf IS 'sigla da unidade federativa';

COMMENT ON COLUMN tb_uf.no_uf IS 'nome da unidade federativa';

CREATE TABLE tb_municipio (
	co_municipio         integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	co_ibge              integer  NOT NULL ,
	no_municipio         varchar(50)  NOT NULL ,
	co_uf                integer  NOT NULL ,
	CONSTRAINT pk_municipio_co_municipio PRIMARY KEY ( co_municipio ),
	CONSTRAINT fk_municipio_uf FOREIGN KEY ( co_uf ) REFERENCES tb_uf( co_ibge )
 );

COMMENT ON COLUMN tb_municipio.co_municipio IS 'chave primaria da tabela';

COMMENT ON COLUMN tb_municipio.co_ibge IS 'código da base do IBGE';

COMMENT ON COLUMN tb_municipio.no_municipio IS 'nome do município';

COMMENT ON COLUMN tb_municipio.co_uf IS 'chave estrangeira para tabela de uf';

CREATE TABLE tb_endereco (
	co_endereco          integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ds_complemento       varchar(255)  NOT NULL ,
	nu_cep               varchar(8)  NOT NULL ,
	ds_logradouro        varchar(255)  NOT NULL ,
	co_municipio         integer  NOT NULL ,
	CONSTRAINT pk_endereco_coendereco PRIMARY KEY ( co_endereco ),
	CONSTRAINT fk_endereco_municipio FOREIGN KEY ( co_municipio ) REFERENCES tb_municipio( co_municipio )
 );

COMMENT ON COLUMN tb_endereco.co_endereco IS 'chave primária da tabela';

COMMENT ON COLUMN tb_endereco.ds_complemento IS 'completo do endereço';

COMMENT ON COLUMN tb_endereco.nu_cep IS 'número do cep';

COMMENT ON COLUMN tb_endereco.ds_logradouro IS 'descrição do logradouro';

COMMENT ON COLUMN tb_endereco.co_municipio IS 'chave estrangeira para tabela que possui dados do ibge';
