/* eslint-disable import/prefer-default-export */
export const OBTER_SEGMENTOS = 'OBTER_SEGMENTOS';
export const OBTER_CRITERIOS = 'OBTER_CRITERIOS';
export const DEFINIR_ORGANIZACAO = 'DEFINIR_ORGANIZACAO';
export const DEFINIR_ORGANIZACOES = 'DEFINIR_ORGANIZACOES';
export const OBTER_DADOS_ORGANIZACAO = 'OBTER_DADOS_ORGANIZACAO';
export const OBTER_DOCUMENTACAO_COMPROBATORIA = 'OBTER_DOCUMENTACAO_COMPROBATORIA';
export const LISTAR_ORGANIZACOES_HABILITACAO = 'LISTAR_ORGANIZACOES_HABILITACAO';
export const DEFINIR_ORGANIZACOES_RECURSO = 'DEFINIR_ORGANIZACOES_RECURSO';
export const MOSTRAR_MODAL_VISUALIZACAO = 'MOSTRAR_MODAL_VISUALIZACAO';
