/* eslint-disable import/prefer-default-export */
export const DEFINIR_REPRESENTANTE = 'DEFINIR_REPRESENTANTE';
export const OBTER_DADOS_REPRESENTANTE = 'OBTER_DADOS_REPRESENTANTE';
export const LISTAR_REPRESENTANTES = 'LISTAR_REPRESENTANTES';
export const LISTAR_REPRESENTANTES_HABILITACAO = 'LISTAR_REPRESENTANTES_HABILITACAO';
